name: Build CTRL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-PreRelease:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    container:
      image: 'devkitpro/devkitarm'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/Build -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/3DS.cmake" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/Build --config Release

      - name: Install
        run: cmake --install ${{github.workspace}}/Build --prefix ${{github.workspace}}/Build/Release

      - name: Make ZIP
        run: |
          (cd ${{github.workspace}}/Build/Release && zip -r CTRL-${{github.sha}}.zip .)
          mv ${{github.workspace}}/Build/Release/CTRL-${{github.sha}}.zip .

      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          name: PreRelease-${{github.sha}}
          files: CTRL-${{github.sha}}.zip
          fail_on_unmatched_files: true
          tag_name: PreRelease-${{github.run_id}}
          prerelease: true
          make_latest: true
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: true